### ISSUE TITLE
Versions of R, Python, and dependencies

### ISSUE THREAD

**Issue by agitter** [gitter-lab/hiv1-aurkb#2]
We should report the versions of R, Python, and the various packages used in the analyses.  Then, we can think about whether to provide an environment for installing all of the required versions.

From the manuscript draft:
- Python 2.7
- R 3.3.2
- limma 3.8
- qvalue 2.12.0

**Comment by csmagnano** [comment]
This is the environment which produced exactly the current results files:

[hivEnv.txt](https://github.com/gitter-lab/hiv1-aurkb/files/10855556/hivEnv.txt)

**Comment by agitter** [comment]
I was able to install the R and Python packages in the environment above through conda using the environment file from 0da7d286d25ff6a688962480c50e990d61f95ddd. The contents of my environment are dumped here:
[hiv1-aurkb-env-2023-03-03.txt](https://github.com/gitter-lab/hiv1-aurkb/files/10885770/hiv1-aurkb-env-2023-03-03.txt)

~I haven't tried rerunning the scripts in this environment yet.~
I also confirmed the scripts run in this environment.

**Comment by agitter** [comment]
This issue will be closed when we merge the `knockout-analysis` branch. We now run all analyses, base and control, in the conda environment and use output files produced from that environment. I updated the manuscript to report package versions matching that environment.
